name: Build

on:
  push:
    branches:
      - master

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: bootstrap vcpkg
              run: ./vcpkg/bootstrap-vcpkg.sh
            
            - name: Install vcpkg dependencies
              run: ./vcpkg/vcpkg install
            
            - name: Cibuildwheel
              uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_ARCHS_MACOS: universal2
                CIBW_ARCHS_WINDOWS: auto ARM64
