name: Build

on:
  push:
    branches:
      - main

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Bootstrap vcpkg
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    ./vcpkg/bootstrap-vcpkg.bat
                  else
                    ./vcpkg/bootstrap-vcpkg.sh
                  fi
              shell: bash
            
            - name: Install vcpkg dependencies
              run: ./vcpkg/vcpkg install
            
            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.16.5
            
            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse
              
