name: Build

on:
  push:
    branches:
      - main

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_ARCHS_MACOS: universal2
                CIBW_ARCHS_WINDOWS: auto ARM64
            
            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.16.5
            
            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse