name: Build

on:
  push:
    branches:
      - main

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Bootstrap vcpkg
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    cmd /c ${GITHUB_WORKSPACE}\vcpkg\bootstrap-vcpkg.bat
                  else
                    bash ${GITHUB_WORKSPACE}/vcpkg/bootstrap-vcpkg.sh
                  fi
              shell: bash
            
            - name: Install vcpkg dependencies
              run: ${GITHUB_WORKSPACE}/vcpkg/vcpkg install
            
            - name: Cibuildwheel
              uses: pypa/cibuildwheel@v2.16
              env:
                CIBW_ARCHS_MACOS: universal2
                CIBW_ARCHS_WINDOWS: auto ARM64
